name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: TechStylersWeb
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
